### ISSUE TITLE
Récuperer les competitions

### ISSUE THREAD

**Issue by vinc-developer** [BlockchainEtSociete/DevFest_CodeLabs#1]
affichages pour les utilisateurs sur une nouvelle page, les compétitions actives et ou inactive
+ refacto de l'event de récuperation des compétitions
+ penser dans le refacto a l'affichage quand un jury recherche les competiions qui lui sont lié

**Comment by devsheder** [comment]
https://github.com/BlockchainEtSociete/DevFest_CodeLabs/pull/24
