### ISSUE TITLE
Creation de l'event de récuperation des Jurys

### ISSUE THREAD

**Issue by vinc-developer** [BlockchainEtSociete/DevFest_CodeLabs#21]

**Comment by devsheder** [comment]
https://github.com/BlockchainEtSociete/DevFest_CodeLabs/pull/24
https://github.com/BlockchainEtSociete/DevFest_CodeLabs/pull/24/files#diff-3a4e32a93220cfd41cec28452a5be1e685604ab02fc65f89b30bc2a5b1b35cacR59
