### ISSUE TITLE
Connexion utilisateur

### ISSUE THREAD

**Issue by vinc-developer** [BlockchainEtSociete/DevFest_CodeLabs#3]
Lors de la connexion avec le wallet, verifier si l'utilisateur est soit un jury ou un administrateur et le diriger sur la page correspondante.
Dans le cas ou le wallet n'est pas reconnu, lui afficher un msg d'erreur.

**Comment by devsheder** [comment]
https://github.com/BlockchainEtSociete/DevFest_CodeLabs/pull/15
