### ISSUE TITLE
Voter pour une compétition

### ISSUE THREAD

**Issue by vinc-developer** [BlockchainEtSociete/DevFest_CodeLabs#5]
Quand un jury ce connecte, il peut voir les compétitions ou il peu voter.
Le jury peu voter une seul fois par compétitions

**Comment by bpresles** [comment]
S'inspirer des contrats Governance.sol du projet DAO (https://github.com/BlockchainEtSociete/DAO/blob/main/hardhat/contracts/governance/Governance.sol) 
et aussi de ce contrat (https://github.com/bpresles/Alyra_Developpeur_Blockchain_Project_3/blob/main/hardhat/contracts/Voting.sol) pour le décompte du vainqueur (qui doit être fait au fur et à mesure et non à la fin, pour éviter les risques d'attaque par overflow. Voir fonction "setVote" et la gestion de la mise à jour du "winningProposalID")

Pour le moment, tu ne mets pas de contrôle sur la validité du votant (i.e: pas de contrôle s'il est un jury de la competition), ni si l'identifiant du nominé est valide pour cette compétition, tu fais juste le mécanisme de vote, c'est à dire:

- Fonction qui permet de voter pour un nominé prenant en paramètre: idCompetition, idNominé
=> La fonction viendra incrémenté le nombre de vote, mettre à jour l'id du gagnant théorique, et emettre un évenement "VoteAdded(msg.sender, idCompetition, idNomine)".
=> Les votes et gagnant doivent être comptabilisées par compétition distinctement (prévoir un mapping (idCompetition => structureAvecDonneesDeVote))

Sache qu'avec Remix (IDE en ligne), on peut appeler les fonctions des smart contracts sans front, en important le contrat via son addresse. Donc on peut tester manuellement les fonctions du contrat ainsi avant même d'avoir codé le front.

**Comment by devsheder** [comment]
Je prends la partie front pour le moment

**Comment by devsheder** [comment]
https://github.com/BlockchainEtSociete/DevFest_CodeLabs/pull/27
